version: '3.8'

services:
  postgres:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-clean-pg
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./backend/data/pg:/data/postgres

  # cache:
  #   container_name: nest-clean-cache
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data
